version: '3'

services:
  core:
    image: core_image
    build: .
    volumes:
      - .:/app
  tests:
    build:
      dockerfile: Dockerfile-test
      context: .
    command: bash -c "prospector && coverage run --source='.' -m unittest discover tests && coverage report"
    volumes:
      - .:/app
